apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kmsvaultsecrets.k8s.patoarvizu.dev
spec:
  group: k8s.patoarvizu.dev
  names:
    kind: KMSVaultSecret
    listKind: KMSVaultSecretList
    plural: kmsvaultsecrets
    singular: kmsvaultsecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            kvSettings:
              properties:
                casIndex:
                  format: int64
                  minimum: 0
                  type: integer
                engineVersion:
                  enum:
                  - v1
                  - v2
                  type: string
              required:
              - engineVersion
              type: object
            path:
              type: string
            secrets:
              items:
                properties:
                  encryptedSecret:
                    type: string
                  key:
                    type: string
                  secretContext:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - key
                - encryptedSecret
                type: object
              type: array
            vaultAuthMethod:
              enum:
              - k8s
              - token
              - userpass
              type: string
          required:
          - path
          - secrets
          - kvSettings
          - vaultAuthMethod
          type: object
        status:
          properties:
            created:
              type: boolean
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
