apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-vault-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kms-vault-operator
  template:
    metadata:
      labels:
        name: kms-vault-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: kms-vault-operator
          image: "patoarvizu/kms-vault-operator:{{ .Values.imageVersion }}"
          command:
          - kms-vault-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: kms-vault-operator
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.accessKeyId.secretName }}
                  key: {{ .Values.aws.accessKeyId.secretKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.secretAccessKey.secretName }}
                  key: {{ .Values.aws.secretAccessKey.secretKey }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: VAULT_ADDR
              value: {{ .Values.vault.address }}
            - name: VAULT_SKIP_VERIFY
              value: {{ .Values.vault.skipVerify | quote }}