version: 2.1

jobs:
  build:
    machine:
        enabled: true
        image: circleci/classic:201808-01
    environment:
      OPERATOR_SDK_VERSION: 0.6.0
      GOPATH: /home/circleci/go
      VAULT_SKIP_VERIFY: 'true'
    working_directory: /home/circleci/go/src/github.com/patoarvizu/kms-vault-operator
    steps:
      - checkout
      - restore_cache:
          keys:
            - kms-vault-operator-golang-cache-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install golang
          command: |
            sudo rm -rf /usr/local/go
            curl -Lo go.linux-amd64.tar.gz "https://dl.google.com/go/go1.11.6.linux-amd64.tar.gz"
            sudo tar -C /usr/local -xzf go.linux-amd64.tar.gz
            mkdir -p ${HOME}/go/bin
            echo 'export PATH="$GOPATH/bin:$PATH"' >> "${BASH_ENV}"
      - run:
          name: Install dep
          command: |
            curl -L https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -o ${HOME}/go/bin/dep
            chmod +x ${HOME}/go/bin/dep
      - run:
          name: Install operator-sdk
          command: |
            curl -L https://github.com/operator-framework/operator-sdk/releases/download/v${OPERATOR_SDK_VERSION}/operator-sdk-v${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -o ${HOME}/go/bin/operator-sdk
            chmod +x ${HOME}/go/bin/operator-sdk
      - run:
          name: Install kubectl
          command: |
            curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            mkdir -p "${HOME}/.kube"
            touch "${HOME}/.kube/config"
      - run:
          name: Install k3d
          command: |
            wget -q -O - https://raw.githubusercontent.com/rancher/k3d/v1.3.1/install.sh | bash
      - run:
          name: Install dependencies
          command: |
            dep ensure -v
      - save_cache:
          key: kms-vault-operator-golang-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - /home/circleci/go/src/github.com/patoarvizu/kms-vault-operator/vendor
      - run:
          name: Run all tests
          command: |
            k3d create --publish 8200:8200 --image rancher/k3s:v0.2.0
            sleep 10
            export KUBECONFIG="$(k3d get-kubeconfig --name=k3s-default)"
            operator-sdk build patoarvizu/kms-vault-operator:latest
            kubectl apply -f test/manifests/vault/vault-external-service.yaml
            kubectl apply -f test/manifests/vault/vault-operator.yaml
            while [ "$(kubectl get deployment vault-operator -o jsonpath={.status.availableReplicas})" != "1" ]; do
              sleep 3
              kubectl get pods -l "name=vault-operator"
            done
            kubectl apply -f test/manifests/vault/vault-cluster-v1.yaml
            while [ "$(kubectl get statefulset vault -o jsonpath={.status.readyReplicas})" != "1" ]; do
              sleep 3
              kubectl get pods -l "app=vault" -l "kv_version=v1"
            done
            operator-sdk test local ./test/e2e/ --namespace "default" --global-manifest ./test/manifests/global/crd.yaml --namespaced-manifest ./test/manifests/namespaced/operator.yaml --go-test-flags '-v -run .*V1'
            kubectl delete -f test/manifests/vault/vault-cluster-v1.yaml
            kubectl apply -f test/manifests/vault/vault-cluster-v2.yaml
            while [ "$(kubectl get statefulset vault -o jsonpath={.status.readyReplicas})" != "1" ]; do
              sleep 3
              kubectl get pods -l "app=vault" -l "kv_version=v2"
            done
            operator-sdk test local ./test/e2e/ --namespace "default" --global-manifest ./test/manifests/global/crd.yaml --namespaced-manifest ./test/manifests/namespaced/operator.yaml --go-test-flags '-v -run .*V2'
      - run:
          name: Build container
          command: |
            echo $DOCKER_HUB_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
            operator-sdk build patoarvizu/kms-vault-operator:$CIRCLE_SHA1
            VERSION=${CIRCLE_TAG:-latest}
            docker tag patoarvizu/kms-vault-operator:$CIRCLE_SHA1 patoarvizu/kms-vault-operator:latest
            docker tag patoarvizu/kms-vault-operator:$CIRCLE_SHA1 patoarvizu/kms-vault-operator:$VERSION
            docker push patoarvizu/kms-vault-operator:$CIRCLE_SHA1
            docker push patoarvizu/kms-vault-operator:$VERSION
            docker push patoarvizu/kms-vault-operator:latest

workflows:
  version: 2
  build-operator:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+.\d+$/